//
// Generated by the Resolve to Java Translator
// from file:  Char_Str_Template.co
// on:         Wed Apr 28 13:08:52 EDT 2010
//
package RESOLVE.Main.Concepts.Standard.Char_Str_Template; 
 
import RESOLVE.*;
import RESOLVE.Main.Concepts.Standard.Boolean_Template.*;
import RESOLVE.Main.Concepts.Standard.Character_Template.*;
import RESOLVE.Main.Concepts.Standard.Integer_Template.*;

public interface Char_Str_Template extends RESOLVE_INTERFACE {

	interface Char_Str extends RType {
	}

	Char_Str_Template.Char_Str  Char_Str_for(Character_Template.Character  c);
	Boolean_Template.Boolean  Are_Equal(Char_Str_Template.Char_Str  s1, Char_Str_Template.Char_Str  s2);
	Boolean_Template.Boolean  Are_Not_Equal(Char_Str_Template.Char_Str  s1, Char_Str_Template.Char_Str  s2);
	Char_Str_Template.Char_Str  Merger(Char_Str_Template.Char_Str  s1, Char_Str_Template.Char_Str  s2);
	Integer_Template.Integer  Length(Char_Str_Template.Char_Str  s);
	Char_Str_Template.Char_Str  Replica(Char_Str_Template.Char_Str  s);
	void Read(Char_Str_Template.Char_Str  c);
	void Write(Char_Str_Template.Char_Str  c);
	void Write_Line(Char_Str_Template.Char_Str  c);
	Char_Str createChar_Str();
	Char_Str createChar_Str(String s);
}
