/*
 * This softare is released under the new BSD 2006 license.
 * 
 * Note the new BSD license is equivalent to the MIT License, except for the
 * no-endorsement final clause.
 * 
 * Copyright (c) 2007, Clemson University
 * 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 *   * Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer. 
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution. 
 *   * Neither the name of the Clemson University nor the names of its
 *     contributors may be used to endorse or promote products derived from
 *     this software without specific prior written permission. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * This sofware has been developed by past and present members of the
 * Reusable Sofware Research Group (RSRG) in the School of Computing at
 * Clemson University.  Contributors to the initial version are:
 * 
 *     Steven Atkinson
 *     Greg Kulczycki
 *     Kunal Chopra
 *     John Hunt
 *     Heather Keown
 *     Ben Markle
 *     Kim Roche
 *     Murali Sitaraman
 */

//
// Generated by the Resolve to Java Translator
// from file:  Character_Template.co
// on:         Tue Sep 12 13:57:49 EDT 2006
//
package RESOLVE.Main.Concepts.Standard.Character_Template; 
 
import RESOLVE.*;
import RESOLVE.Main.Concepts.Standard.Boolean_Template.*;
import RESOLVE.Main.Concepts.Standard.Integer_Template.*;

public interface Character_Template extends RESOLVE_INTERFACE {

	interface Character extends RType {
	}

	Integer_Template.Integer  Char_to_Int(Character_Template.Character  c);
	Boolean_Template.Boolean  Are_Equal(Character_Template.Character  c1, Character_Template.Character  c2);
	Boolean_Template.Boolean  Are_Not_Equal(Character_Template.Character  c1, Character_Template.Character  c2);
	Boolean_Template.Boolean  Less_Or_Equal(Character_Template.Character  c1, Character_Template.Character  c2);
	Boolean_Template.Boolean  Less(Character_Template.Character  c1, Character_Template.Character  c2);
	Boolean_Template.Boolean  Greater_Or_Equal(Character_Template.Character  c1, Character_Template.Character  c2);
	Boolean_Template.Boolean  Greater(Character_Template.Character  c1, Character_Template.Character  c2);
	Character_Template.Character  Replica(Character_Template.Character  c);
	void Read(Character_Template.Character  c);
	void Write(Character_Template.Character  c);
	void Write_Line(Character_Template.Character  c);
	Character createCharacter();
	Character createCharacter(char c);
	// this operation here only for the use of Std_Char_Str_Realiz to convert a Character to Char_Str
  	public String Make_String(Character_Template.Character c);
}
