//
// Generated by the Resolve to Java Translator
// from file:  /home/webapps/new-working-dir/workspaces/Default_Project/RESOLVE/Main/Concepts/Standard/Boolean_Template/Boolean_Template.co
// on:         Sat Jan 05 01:20:31 EST 2013
//
package RESOLVE.Main.Concepts.Standard.Boolean_Template; 
 
import RESOLVE.*;

public interface Boolean_Template extends RESOLVE_INTERFACE {

	interface Boolean extends RType {
	}

	Boolean_Template.Boolean  True();
	Boolean_Template.Boolean  False();
	Boolean_Template.Boolean  And(Boolean_Template.Boolean  b1, Boolean_Template.Boolean  b2);
	Boolean_Template.Boolean  Or(Boolean_Template.Boolean  b1, Boolean_Template.Boolean  b2);
	Boolean_Template.Boolean  Not(Boolean_Template.Boolean  b);
	Boolean_Template.Boolean  Are_Equal(Boolean_Template.Boolean  b1, Boolean_Template.Boolean  b2);
	Boolean_Template.Boolean  Are_Not_Equal(Boolean_Template.Boolean  b1, Boolean_Template.Boolean  b2);
	Boolean_Template.Boolean  Replica(Boolean_Template.Boolean  b);
	void Read(Boolean_Template.Boolean  b);
	void Write(Boolean_Template.Boolean  b);
	void Write_Line(Boolean_Template.Boolean  b);
	Boolean createBoolean();
}
