/**
 * This class was automatically generated by the RESOLVE to Java
 * translator. This file should not be modified.
 */
package RESOLVE.Main.Concepts.Standard.Boolean_Template;

import RESOLVE.*;

public interface Boolean_Template extends RESOLVE_INTERFACE {
	interface Boolean extends RType {
	}
    public Boolean_Template.Boolean createBoolean();
    public Boolean_Template.Boolean True();
    public Boolean_Template.Boolean False();
    public Boolean_Template.Boolean And(Boolean_Template.Boolean b1, Boolean_Template.Boolean b2);
    public Boolean_Template.Boolean Or(Boolean_Template.Boolean b1, Boolean_Template.Boolean b2);
    public Boolean_Template.Boolean Not(Boolean_Template.Boolean b);
    public Boolean_Template.Boolean Are_Equal(Boolean_Template.Boolean b1, Boolean_Template.Boolean b2);
    public Boolean_Template.Boolean Are_Not_Equal(Boolean_Template.Boolean b1, Boolean_Template.Boolean b2);
    public Boolean_Template.Boolean Replica(Boolean_Template.Boolean b);
    public void Read(Boolean_Template.Boolean b);
    public void Write(Boolean_Template.Boolean b);
    public void Write_Line(Boolean_Template.Boolean b);
}